name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: '22'
  YARN_FLAGS: '${{ vars.YARN_FLAGS || '''' }}'

jobs:
  lint:
    name: Lint
    uses: AdGuardSoftwareLimited/actions/.github/workflows/lint.yml@master
    with:
      runs-on: '["ubuntu-latest"]'
      prepare-script: 'corepack enable && yarn install --frozen-lockfile'
      lint-command: 'yarn lint'

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Enable Yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile ${{ env.YARN_FLAGS }}

      - name: Run tests
        run: yarn test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Enable Yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile ${{ env.YARN_FLAGS }}

      - name: Build
        run: yarn build
