name: Build

on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
    branches:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Lint
    uses: AdGuardSoftwareLimited/actions/.github/workflows/lint.yml@master
    with:
      runs-on: '["team-extensions"]'
      prepare-script: |
        docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          adguard/node-ssh:22.17--0 \
          yarn install --frozen-lockfile
      lint-command: |
        docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          adguard/node-ssh:22.17--0 \
          yarn lint

  test:
    name: Test
    needs: lint
    uses: AdGuardSoftwareLimited/actions/.github/workflows/junit-tests.yml@master
    secrets: inherit
    with:
      runs-on: '["team-extensions"]'
      prepare-script: |
        docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          adguard/node-ssh:22.17--0 \
          yarn install --frozen-lockfile
      test-command: |
        docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          adguard/node-ssh:22.17--0 \
          yarn test
      results-path: 'test-results/junit.xml'
